# Generated by Django 2.2.2 on 2019-06-12 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_permission_permission_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='licence',
        ),
        migrations.AddField(
            model_name='company',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license', to='companies.License'),
        ),
    ]
