# Generated by Django 2.2.2 on 2019-06-12 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20190612_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licence', to='companies.License'),
        ),
    ]
