# Generated by Django 2.2.2 on 2019-06-12 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20190612_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission_role',
            name='has_perm',
        ),
        migrations.AlterField(
            model_name='company',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.License'),
        ),
        migrations.AlterField(
            model_name='permission_role',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Role'),
        ),
    ]
